SALES_CALLBACK = 'SALES_CALLBACK'
HIRING_CALLBACK = 'HIRING_CALLBACK'

BOROVOE_CALLBACK = 'BOROVOE_CALLBACK'
KOKSHETAU_CALLBACK = 'KOKSHETAU_CALLBACK'
SHUCHINSK_CALLBACK = 'SHUCHINSK_CALLBACK'

CITIES_CALLBACK = [KOKSHETAU_CALLBACK, SHUCHINSK_CALLBACK, BOROVOE_CALLBACK, SALES_CALLBACK]

SORT_CALLBACK = 'SORT_CALLBACK'
TRIM_CALLBACK = 'TRIM_CALLBACK'
OTHER_CALLBACK = 'OTHER_CALLBACK'
SHPEK_CALLBACK = 'SHPEK_CALLBACK'
INDUS_CALLBACK = 'INDUS_CALLBACK'
CENTER_CALLBACK = 'CENTER_CALLBACK'
GASHISH_CALLBACK = 'GASHISH_CALLBACK'

GOODS_CALLBACKS = [SORT_CALLBACK, INDUS_CALLBACK, TRIM_CALLBACK, CENTER_CALLBACK, SHPEK_CALLBACK, GASHISH_CALLBACK, OTHER_CALLBACK]

BACK_CALLBACK = 'BACK_CALLBACK'
